config/routes.rb
Rails.application.routes.draw do
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id', to: 'users#show', as: 'user'
  resources :page_informations
  resources :annotations, except: :destroy
  get 'art_item_images/index'
  resources :art_items do
    resources :art_item_images, only: :index
  end
  resources :accesses
  resources :permissions
  resources :departments
  resources :appraisal_types
  resources :roles
  resources :reports, only: [] do
    collection do
      get :art_items
    end
  end

  get 'art_items/delete_file_attachment/:id', to: 'art_items#delete_file_attachment', as: :delete_file

  get 'static_pages/home'

  # Sentry test endpoint (only available in staging and production)
  if Rails.env.staging? || Rails.env.production?
    get 'sentry-test', to: 'static_pages#sentry_test'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "static_pages#home"

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :super_user_department_admin_access_authorized!
  before_action :set_access, only: %i[ show edit update destroy ]
  before_action :get_permissions, only: %i[ new edit ]

  # GET /accesses or /accesses.json
  def index
    @accesses = get_accesses_collection.sort_by { |ac| ac.permission.department_full_name }
  end

  # GET /accesses/1 or /accesses/1.json
  def show
  end

  # GET /accesses/new
  def new
    @access = Access.new
  end

  # GET /accesses/1/edit
  def edit
  end

  # POST /accesses or /accesses.json
  def create
    @access = Access.new(access_params)

    respond_to do |format|
      if @access.save
        format.html { redirect_to access_url(@access), notice: "Access was successfully created." }
        format.json { render :show, status: :created, location: @access }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accesses/1 or /accesses/1.json
  def update
    respond_to do |format|
      if @access.update(access_params)
        format.html { redirect_to access_url(@access), notice: "Access was successfully updated." }
        format.json { render :show, status: :ok, location: @access }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1 or /accesses/1.json
  def destroy
    @access.destroy

    respond_to do |format|
      format.html { redirect_to accesses_url, notice: "Access was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access
      @access = Access.find(params[:id])
    end

    def get_permissions
      @permissions_available = current_user_associated_department_permissions
    end

    # Only allow a list of trusted parameters through.
    def access_params
      params.require(:access).permit(:permission_id, :uniqname, :updated_by)
    end
end

app/views/accesses/_access.html.erb
<div id="<%= dom_id access %>">

  <p class="my-5">
    <strong class="block font-medium mb-1">Department:</strong>
    <%= show_department_fullname(access.permission.department_id) %> - <%= show_role_title(access.permission.role_id) %>
  </p>

  <p>
    <strong class="block font-medium mb-1">User:</strong>
    <%= show_user_name_by_uniqname(access.uniqname) %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Updated by:</strong>
    <%= show_user_name_by_id(access.updated_by) %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show", access, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit', edit_access_path(access), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/accesses/_form.html.erb
<%= form_with(model: access, class: "contents") do |form| %>
  <% if access.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
        <% access.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :updated_by, value: current_user.id %>

  <div class="my-5">
    <%= form.label :permission_id %>
    <%= form.collection_select :permission_id, @permissions_available.sort_by { |p| p.department_full_name }, :id, :department_name_and_role_title, prompt: true %>
  </div>

  <div class="my-5">
    <%= form.label :uniqname %>
    <%= form.text_field :uniqname, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-900 text-white inline-block font-medium cursor-pointer hover:bg-white hover:text-blue-umblue hover:ring-2 hover:ring-blue-umblue" %>
  </div>
<% end %>

app/views/accesses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing User Access</h1>

  <%= render "form", access: @access %>

  <%= link_to "Show", @access, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back", accesses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/accesses/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Users Access</h1>
      <%= render 'layouts/display_info_text', location: 'accesses' %>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to 'Add User', new_access_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-blue-umblue px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-white hover:text-blue-umblue hover:ring-2 hover:ring-blue-umblue focus:outline-none focus:ring-2 focus:ring-blue-umblue focus:ring-offset-2 sm:w-auto" %>
    </div>
  </div>
  <div class="-mx-4 mt-8 overflow-x-auto shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
    <table class="min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Permission</th>
          <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Uniqname</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Updated by</th>
          <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
            <span class="sr-only">Edit</span>
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
      <% @accesses.each do |access| %>
        <tr class="even:bg-blue-50">
          <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900 lg:table-cell lg:pl-6"><%= show_department_fullname(access.permission.department_id) %> - <%= show_role_title(access.permission.role_id) %></td>
          <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900"><%= show_user_name_by_uniqname(access.uniqname) %></td>
          <td class="hidden whitespace-nowrap px-3 py-4 text-sm text-gray-500 lg:table-cell"><%= show_user_name_by_id(access.updated_by) %></td>
          <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
            <%= link_to "Show", access_path(access), class: "text-indigo-600 hover:text-indigo-900" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accesses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New User Access</h1>

  <%= render "form", access: @access %>

  <%= link_to 'Back', accesses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/accesses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @access %>

    <%= link_to 'Edit', edit_access_path(@access), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy', access_path(@access), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back', accesses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>