config/routes.rb
Rails.application.routes.draw do
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id', to: 'users#show', as: 'user'
  resources :page_informations
  resources :annotations, except: :destroy
  get 'art_item_images/index'
  resources :art_items do
    resources :art_item_images, only: :index
  end
  resources :accesses
  resources :permissions
  resources :departments
  resources :appraisal_types
  resources :roles
  resources :reports, only: [] do
    collection do
      get :art_items
    end
  end

  get 'art_items/delete_file_attachment/:id', to: 'art_items#delete_file_attachment', as: :delete_file

  get 'static_pages/home'

  # Sentry test endpoint (only available in staging and production)
  if Rails.env.staging? || Rails.env.production?
    get 'sentry-test', to: 'static_pages#sentry_test'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "static_pages#home"

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
end

app/models/annotation.rb
# == Schema Information
#
# Table name: annotations
#
#  id          :bigint           not null, primary key
#  updated_by  :integer
#  art_item_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Annotation < ApplicationRecord
  belongs_to :art_item
  has_rich_text :note

  validates_presence_of :note
  validates :updated_by, presence: true

end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :check_for_authorized_access
  before_action :set_annotation, only: %i[ show edit update destroy ]


  # GET /annotations or /annotations.json
  def index
    @annotations = Annotation.all
  end

  # GET /annotations/1 or /annotations/1.json
  def show
  end

  # GET /annotations/new
  def new
    @new_annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit
  end

  # POST /annotations or /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)
    if @annotation.save
      @annotations = Annotation.where(art_item: @annotation.art_item).order("updated_at DESC")
      @new_annotation = Annotation.new(art_item: @annotation.art_item)
      flash.now[:notice] = "Annotation successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /annotations/1 or /annotations/1.json
  def update
    if @annotation.update(annotation_params)
      @annotations = Annotation.where(art_item: @annotation.art_item).order("updated_at DESC")
      flash.now[:notice] = "Annotation successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def annotation_params
      params.require(:annotation).permit(:note, :updated_by, :art_item_id)
    end
end

app/views/annotations/_annotation.html.erb
<%= turbo_frame_tag annotation do %>
  <hr class= "flex-1 border-t border-blue-600 my-1">
  <div>
    <div class="w-full ">
      <div class="flex body-lg-text space-x-2 items-center pt-1">
        <div><%= annotation.note %></div>
      </div>
      <div class="flex items-center body-text">
        <div>
          Updated on: 
          <%= annotation.updated_at.strftime('%m/%d/%Y') %>
        </div>
        <div class="flex items-center pl-1 body-text">
          <%= show_user_name_by_id(annotation.updated_by) %>
            <%= link_to "Edit", edit_annotation_path(annotation), class: "pl-2 link-text" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/annotations/_form.html.erb
<%= form_with(model: annotation) do |form| %>
  <% if annotation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
        <% annotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.hidden_field :updated_by, value: current_user.id %>

  <div class="my-5">
    <%= form.rich_text_area :note, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :art_item_id, value: annotation.art_item_id %>

  <% if annotation.new_record? %>
    <%= form.submit "Add Annotation", class: "secondary_blue_button" %>
  <% else %>
    <div>
      <%= form.submit "Update", class: "secondary_blue_button" %>
      <%= link_to "Cancel", @annotation, class: "link-text" %>
    </div>
  <% end %>
<% end %>

app/views/annotations/create.turbo_stream.erb
<%= turbo_stream.prepend "annotations", @annotation %>

<%= turbo_stream.update "new_annotation" do %>
  <%= render "form", annotation: @new_annotation %>
<% end %>

<%= render_flash_stream %>

app/views/annotations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing annotation</h1>

  <%= turbo_frame_tag @annotation do %>
    <%= render "form", annotation: @annotation %>
  <% end %>
</div>

app/views/annotations/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Annotations</h1>
    <%= link_to 'New annotation', new_annotation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="annotations" class="min-w-full">
    <%= render @annotations %>
  </div>
</div>

app/views/annotations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New annotation</h1>

  <%= turbo_frame_tag "new_annotation" do %>
    <%= render "form", annotation: @annotation %>
  <% end %>

</div>

app/views/annotations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @annotation %>

    <%= link_to 'Edit this annotation', edit_annotation_path(@annotation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this annotation', annotation_path(@annotation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to annotations', annotations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/annotations/update.turbo_stream.erb
<%= turbo_stream.replace @annotation, @annotation %>

<%= render_flash_stream %>